service:
  name: "ec2-management-and-monitoring"
  publish: false # disable auto-publishing to the Serverless platform

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-pseudo-parameters
  - serverless-webpack


package:
  individually: true

#functions:
#  rotate_volume_snapshots_based_on_tags:
#    handler: "app.init" # required, handler set in AWS Lambda
#    name: "${self:custom.name}-app" # optional, Deployed Lambda name
#    description: ${self:custom.name} application run out of lambda # optional, Description to publish to AWS


provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}

custom:
  name: "${self:service}-${self:provider.stage}"
  nameU: "nurture_repositories_${self:provider.stage}"
  accountId: 835550300439


resources: ${file(./rolesPolicies.yml)}